CREATE DATABASE RENT_BOOK
GO
USE RENT_BOOK
GO

SET DATEFORMAT dmy
GO

CREATE TABLE NguoiDung
(
	ND_ID INT IDENTITY NOT NULL,
	TenDangNhap NVARCHAR(20),
	MatKhau NVARCHAR(45),
	HoTen NVARCHAR(255),
	Email NVARCHAR(45),
	DiaChi NVARCHAR(255),
	NgaySinh DATE,
	GioiTinh NVARCHAR(20),

	PRIMARY KEY(ND_ID)
)
GO

CREATE TABLE LoaiSach
(
	LS_ID INT IDENTITY NOT NULL,
	Ten NVARCHAR(100),
	MoTa NVARCHAR(255),

	PRIMARY KEY(LS_ID)
)
GO

CREATE TABLE Sach
(
	S_ID INT IDENTITY NOT NULL,
	TieuDe NVARCHAR(255),
	TacGia NVARCHAR(255),
	NamXuatBan INT,
	LS_ID INT,
	MoTa NVARCHAR(255),

	PRIMARY KEY(S_ID),
	CONSTRAINT FK_Sach_LoaiSach FOREIGN KEY (LS_ID) REFERENCES LoaiSach(LS_ID)
)
GO


CREATE TABLE HoaDon
(
	HD_ID INT IDENTITY NOT NULL,
	Ngay DATE,
	NhanVien NVARCHAR(255),
	TenKhachHang NVARCHAR(255),
	GhiChu NVARCHAR(255),

	PRIMARY KEY(HD_ID)
)
GO

CREATE TABLE ChiTietHoaDon
(
	CTHD_ID INT IDENTITY NOT NULL,
	HD_ID INT,
	S_ID INT,
	SoLuong INT,
	GiaBan FLOAT,

	PRIMARY KEY(CTHD_ID),
	CONSTRAINT FK_ChiTietHoaDon_HoaDon FOREIGN KEY (HD_ID) REFERENCES HoaDon(HD_ID),
	CONSTRAINT FK_ChiTietHoaDon_Sach FOREIGN KEY (S_ID) REFERENCES Sach(S_ID)
)
GO

CREATE TABLE PhieuNhapSach
(
	PNS_ID INT IDENTITY NOT NULL,
	GhiChu NVARCHAR(255),
	Ngay DATE,
	NhanVien NVARCHAR(255),

	PRIMARY KEY(PNS_ID)
)
GO

CREATE TABLE ChiTietPhieuNhapSach
(
	CTPNS_ID INT IDENTITY NOT NULL,
	PNS_ID INT,
	S_ID INT,
	SoLuong INT,
	GiaBan FLOAT,

	PRIMARY KEY(CTPNS_ID),
	CONSTRAINT FK_ChiTietPhieuNhapSach_PhieuNhapSach FOREIGN KEY (PNS_ID) REFERENCES PhieuNhapSach(PNS_ID),
	CONSTRAINT FK_ChiTietPhieuNhapSach_Sach FOREIGN KEY (S_ID) REFERENCES Sach(S_ID)
)
GO
