import java.util.ArrayList;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class FormChuyenTien extends javax.swing.JFrame {
        ArrayList<TaiKhoan> lstChuyenTien = new ArrayList<>();
    private volatile boolean isRunning = true;
    private Thread dataCreationThread;

    public FormChuyenTien() {
        initComponents();
    }

    private void createData() throws InterruptedException {
        for(int i = 1; i< 2000; i++) {
            int rNum1 = (int)(Math.random()*100)+1;
            int rNum2 = (int)(Math.random()*100)+1;
            rNum2 = rNum1==rNum2?rNum2 +1 : rNum2;
            TaiKhoan tk = new TaiKhoan("Thread" + i,(int) (Math.random()*(100000-5000+1))+5000, rNum1, rNum2, 100000);
            lstChuyenTien.add(tk);

            handleTask();
        }
    }

    private void handleTask() throws InterruptedException {
        for(TaiKhoan tk : lstChuyenTien) {
            if(!isRunning) 
                break;
            Runnable task = new ChuyenTienTask(tk);
            Thread t = new Thread(task);
            t.start(); 
        }
    }

    private void hienthi() {
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("Thread Name");
        dtm.addColumn("Số tiền chuyển");
        dtm.addColumn("Chuyển từ tài khoản");
        dtm.addColumn("Chuyển tới tài khoản");
        dtm.addColumn("Tổng tiền trong ngân hàng");
        dtm.setNumRows(lstChuyenTien.size());

        for(int i = 0; i < lstChuyenTien.size(); i++) {
            TaiKhoan ct = lstChuyenTien.get(i);
            dtm.setValueAt(ct.threadName, i, 0);
            dtm.setValueAt(ct.soTienChuyen, i, 1);
            dtm.setValueAt(ct.chuyenTuTK, i, 2);
            dtm.setValueAt(ct.chuyenToiTK, i, 3);
            dtm.setValueAt(ct.tongTien, i, 4);
        }
        this.jTable1.setModel(dtm);
    }

    public void startDataCreationThread() {
        dataCreationThread = new Thread(() -> {
            try {
                createData();
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        });
        dataCreationThread.start();
    }

    public void stopAndDisplayData() {
        isRunning = false;
        try {
            dataCreationThread.join();
        } catch(InterruptedException ex) {
            ex.printStackTrace();
        }
        hienthi();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnStart = new javax.swing.JButton();
        btnSttop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Minh họa chuyển tiền");

        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnSttop.setText("Stop");
        btnSttop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSttopActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Thread Name", "Số tiền chuyển", "Chuyển từ tài khoản", "Chuyển tới tài khoản", "Tổng tiền trong tài khoản"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(btnStart)
                        .addGap(27, 27, 27)
                        .addComponent(btnSttop))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnSttop))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed

        startDataCreationThread();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnSttopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSttopActionPerformed

        stopAndDisplayData();
    }//GEN-LAST:event_btnSttopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormChuyenTien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormChuyenTien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnSttop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
