/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import DAO.DAO_SinhVien;


import POJO.SinhVienPOJO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ngoc thai
 */
public class QLSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QLSinhVien
     */
    public QLSinhVien() {
        initComponents();
        LoadDataToTable();
        cbo_gioitinh.setModel(new DefaultComboBoxModel<>(new String[] {"Gender", "Male","Other"}));
        txt_masv.setEditable(false);
                jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                if (!event.getValueIsAdjusting()) {
                    showSelectedRowData(jTable1);
                }
            }
        });
    }
      private void LoadDataToTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        ArrayList<SinhVienPOJO> listSV = DAO_SinhVien.getInstance().ShowAll();
        for (SinhVienPOJO sv : listSV) {
            model.addRow(new Object[]{sv.getId(), sv.getFirstName(), sv.getLastName(), sv.getGender(), sv.getPhoneNumber(), sv.getBirthday()});
        }
    }
      private void showSelectedRowData(JTable table) {
    int selectedRowIndex = table.getSelectedRow();
    if (selectedRowIndex >= 0) {
        txt_masv.setText(table.getValueAt(selectedRowIndex, 0).toString());
        txt_firstName.setText(table.getValueAt(selectedRowIndex, 1).toString());
        txt_lastName.setText(table.getValueAt(selectedRowIndex, 2).toString());
        // Hiển thị giới tính
        String gender = table.getValueAt(selectedRowIndex, 3).toString();
        cbo_gioitinh.setSelectedItem(gender);
        txt_phone.setText(table.getValueAt(selectedRowIndex, 4).toString());
        // Hiển thị ngày sinh
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        Date birthday;
        try {
            birthday = sdf.parse(table.getValueAt(selectedRowIndex, 5).toString());
            txt_NgaySinh.setText(sdf.format(birthday));
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
    }
}
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jtable_SV = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpanel_SV = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_masv = new javax.swing.JTextField();
        txt_firstName = new javax.swing.JTextField();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        cbo_gioitinh = new javax.swing.JComboBox<>();
        txt_lastName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btn_them = new javax.swing.JButton();
        btn_capnhap = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_clear = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SV", "Họ ", "Tên", "Giới tính", "Số điện thoại", "Ngày sinh"
            }
        ));
        Jtable_SV.setViewportView(jTable1);

        jpanel_SV.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sách"));

        jLabel7.setText("Mã sinh viên");

        jLabel8.setText("Họ");

        jLabel9.setText("Số điện thoại");

        jLabel10.setText("Giói tính");

        jLabel11.setText("Ngày sinh");

        cbo_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbo_gioitinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_gioitinhActionPerformed(evt);
            }
        });

        jLabel12.setText("Tên");

        javax.swing.GroupLayout jpanel_SVLayout = new javax.swing.GroupLayout(jpanel_SV);
        jpanel_SV.setLayout(jpanel_SVLayout);
        jpanel_SVLayout.setHorizontalGroup(
            jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_SVLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_masv)
                    .addComponent(txt_NgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(txt_lastName))
                .addGap(30, 30, 30)
                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_phone)
                        .addComponent(cbo_gioitinh, 0, 187, Short.MAX_VALUE))
                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111))
        );
        jpanel_SVLayout.setVerticalGroup(
            jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_SVLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanel_SVLayout.createSequentialGroup()
                        .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_SVLayout.createSequentialGroup()
                                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_masv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12)
                                    .addComponent(txt_lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_SVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(cbo_gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        btn_them.setText("Thêm");
        btn_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themActionPerformed(evt);
            }
        });

        btn_capnhap.setText("cập nhật");
        btn_capnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhapActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_clear.setText("Làm mới");
        btn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clearActionPerformed(evt);
            }
        });

        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Jtable_SV, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jpanel_SV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(btn_them, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_capnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_clear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(btn_thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(597, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Jtable_SV, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jpanel_SV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_them)
                        .addComponent(btn_xoa)
                        .addComponent(btn_capnhap)
                        .addComponent(btn_clear))
                    .addComponent(btn_thoat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
          int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        SinhVienPOJO svToDelete = new SinhVienPOJO();
        svToDelete.setId((int) jTable1.getValueAt(selectedRow, 0));
        int result = DAO_SinhVien.getInstance().Xoa(svToDelete);
        if (result > 0) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.removeRow(selectedRow);
            JOptionPane.showMessageDialog(this, "Đã xóa sinh viên thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa sinh viên thất bại!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một sinh viên để xóa!");
    }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themActionPerformed
     String firstName = txt_firstName.getText();
    String lastName = txt_lastName.getText();
    String gender = cbo_gioitinh.getSelectedItem().toString();
    String phoneNumber = txt_phone.getText();
    String birthdayString = txt_NgaySinh.getText();

    // Chuyển chuỗi ngày sinh sang định dạng Date
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    Date birthday = null;
    try {
        birthday = sdf.parse(birthdayString);
    } catch (ParseException ex) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh theo định dạng yyyy-MM-dd", "Lỗi", JOptionPane.ERROR_MESSAGE);
        return; // Thoát khỏi phương thức nếu ngày sinh không hợp lệ
    }
    SinhVienPOJO svToAdd = new SinhVienPOJO(0, firstName, lastName, gender, phoneNumber, birthday);
   
    // Thêm sinh viên mới vào cơ sở dữ liệu
int result = DAO_SinhVien.getInstance().Them(svToAdd);

// Kiểm tra kết quả thêm sinh viên
if (result > 0) {
    // Nếu thành công, cập nhật bảng với sinh viên mới
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.addRow(new Object[]{svToAdd.getId(), svToAdd.getFirstName(), svToAdd.getLastName(), svToAdd.getGender(), svToAdd.getPhoneNumber(), svToAdd.getBirthday()});
    JOptionPane.showMessageDialog(this, "Đã thêm sinh viên thành công!");
} else {
    // Nếu thất bại, hiển thị thông báo
    JOptionPane.showMessageDialog(this, "Thêm sinh viên thất bại!");
}
    }//GEN-LAST:event_btn_themActionPerformed

    private void btn_capnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhapActionPerformed
      int selectedRow = jTable1.getSelectedRow();
    if (selectedRow != -1) {
        int studentId = Integer.parseInt(txt_masv.getText());
        String firstName = txt_firstName.getText();
        String lastName = txt_lastName.getText();
        String gender = cbo_gioitinh.getSelectedItem().toString();
        String phoneNumber = txt_phone.getText();
        java.util.Date birthday = null;
          try {
              birthday = new SimpleDateFormat("yyyy-MM-dd").parse(txt_NgaySinh.getText());
          } catch (ParseException ex) {
              Logger.getLogger(QLSinhVien.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        SinhVienPOJO svToUpdate = new SinhVienPOJO(studentId, firstName, lastName, gender, phoneNumber, birthday);
        int result = DAO_SinhVien.getInstance().Sua(svToUpdate);
        if (result > 0) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setValueAt(studentId, selectedRow, 0);
            model.setValueAt(firstName, selectedRow, 1);
            model.setValueAt(lastName, selectedRow, 2);
            model.setValueAt(gender, selectedRow, 3);
            model.setValueAt(phoneNumber, selectedRow, 4);
            model.setValueAt(birthday, selectedRow, 5);
            JOptionPane.showMessageDialog(this, "Đã cập nhật sinh viên thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật sinh viên thất bại!");
        }
    } else {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn một sinh viên để cập nhật!");
    }
    }//GEN-LAST:event_btn_capnhapActionPerformed

    private void btn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clearActionPerformed
        txt_masv.setText("");
    txt_firstName.setText("");
    txt_lastName.setText("");
    cbo_gioitinh.setSelectedIndex(0);
    txt_phone.setText("");
    txt_NgaySinh.setText(""); // Clear ngày sinh
    }//GEN-LAST:event_btn_clearActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
          // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Bạn có muốn đóng không?", "Xác nhận đóng", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.dispose();

           
        }
    }//GEN-LAST:event_btn_thoatActionPerformed

    private void cbo_gioitinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_gioitinhActionPerformed
           
    }//GEN-LAST:event_cbo_gioitinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Jtable_SV;
    private javax.swing.JButton btn_capnhap;
    private javax.swing.JButton btn_clear;
    private javax.swing.JButton btn_them;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_gioitinh;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpanel_SV;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_firstName;
    private javax.swing.JTextField txt_lastName;
    private javax.swing.JTextField txt_masv;
    private javax.swing.JTextField txt_phone;
    // End of variables declaration//GEN-END:variables
}
