/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom11_qltrasua;

import Model.PhanQuyen;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Nguyen Cat Tuong
 */
public class frmMainNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form frmMainNhanVien
     */
    public frmMainNhanVien() {
        initComponents();
//        hienThiTenNhanVien();
        showLogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblLogoNV = new javax.swing.JLabel();
        btnOrderNV = new javax.swing.JButton();
        btnDsKhachHang = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnNhapSanPham = new javax.swing.JButton();
        btnDsTraSuaNV = new javax.swing.JButton();
        btnDsHoaDon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Màn hình chính nhân viên");

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trà sữa 11 Central");

        lblLogoNV.setText("Logo");

        btnOrderNV.setBackground(new java.awt.Color(51, 102, 255));
        btnOrderNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom11_qltrasua/order.png"))); // NOI18N
        btnOrderNV.setText("Order trà sữa");
        btnOrderNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderNVActionPerformed(evt);
            }
        });

        btnDsKhachHang.setBackground(new java.awt.Color(51, 51, 255));
        btnDsKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/khachhang.png"))); // NOI18N
        btnDsKhachHang.setText("Danh sách khách hàng");
        btnDsKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsKhachHangActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setForeground(new java.awt.Color(51, 0, 51));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnNhapSanPham.setBackground(new java.awt.Color(51, 51, 255));
        btnNhapSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom11_qltrasua/product.png"))); // NOI18N
        btnNhapSanPham.setText("Nhập sản phẩm");
        btnNhapSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapSanPhamActionPerformed(evt);
            }
        });

        btnDsTraSuaNV.setBackground(new java.awt.Color(51, 51, 255));
        btnDsTraSuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/product.png"))); // NOI18N
        btnDsTraSuaNV.setText("Danh sách trà sữa");
        btnDsTraSuaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsTraSuaNVActionPerformed(evt);
            }
        });

        btnDsHoaDon.setBackground(new java.awt.Color(51, 51, 255));
        btnDsHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bill.png"))); // NOI18N
        btnDsHoaDon.setText("Danh sách hóa đơn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNhapSanPham, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDsKhachHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOrderNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDsHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDsTraSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblLogoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDsHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOrderNV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDsKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDsTraSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNhapSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderNVActionPerformed
        // TODO add your handling code here:
        frmDatTraSua datTraSua = new frmDatTraSua();
        datTraSua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOrderNVActionPerformed

    private void btnDsKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsKhachHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDsKhachHangActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frmDangNhap Login = new frmDangNhap();
        PhanQuyen.xoaPhanQuyen();
        Login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnNhapSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapSanPhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhapSanPhamActionPerformed

    private void btnDsTraSuaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsTraSuaNVActionPerformed
       
            // TODO add your handling code here:
            frmDanhSachTraSua danhSachTraSua = null;
        try {
            danhSachTraSua = new frmDanhSachTraSua();
            danhSachTraSua.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmMainNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMainNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        

    }//GEN-LAST:event_btnDsTraSuaNVActionPerformed

    
    private void showLogo()
    {
          ImageIcon imageIcon = new ImageIcon("src\\Img\\Logo.png");
              Image image = imageIcon.getImage().getScaledInstance(235,230, Image.SCALE_SMOOTH);
              lblLogoNV.setIcon(new ImageIcon(image));
              return;
    }
//      private void hienThiTenNhanVien()
//    {
//        PhanQuyen phanQuyen = new PhanQuyen();
//        lblNhanVien.setText("welcome: " + phanQuyen.getTaiKhoanCu() );
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMainNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMainNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMainNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMainNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMainNhanVien().setVisible(true);
            }
        });
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDsHoaDon;
    private javax.swing.JButton btnDsKhachHang;
    private javax.swing.JButton btnDsTraSuaNV;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNhapSanPham;
    private javax.swing.JButton btnOrderNV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogoNV;
    // End of variables declaration//GEN-END:variables
}
