/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom11_qltrasua;

import Model.NhanVien;
import Model.PhanQuyen;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Cat Tuong
 */

public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    NhanVien nhanVien = new NhanVien();
    public int admin = 0;
    public static String co= null;
   
    public   frmMain (String co)
    {
        initComponents();
        showLogoStore();
        if(!co.substring(0, 5).equals("admin"))
        {
            btnDanSachNhaCungCap.setEnabled(false);
            admin = 1;
//                    hienThiTenNhanVien();

            
        }
       
    }
    public  frmMain()
    {
        initComponents();
        showLogoStore();
//        hienThiTenNhanVien();
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnOrder = new javax.swing.JButton();
        btnDsNhanVien = new javax.swing.JButton();
        btnDsKhachHang = new javax.swing.JButton();
        btnDanSachNhaCungCap = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnDsHoaDon = new javax.swing.JButton();
        btnDsTraSua = new javax.swing.JButton();
        btnNhapSanPham = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Màn hình chính");

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));

        btnOrder.setBackground(new java.awt.Color(51, 102, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom11_qltrasua/order.png"))); // NOI18N
        btnOrder.setText("Order trà sữa");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        btnDsNhanVien.setBackground(new java.awt.Color(51, 51, 255));
        btnDsNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/employees.png"))); // NOI18N
        btnDsNhanVien.setText("Danh sách nhân viên");
        btnDsNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsNhanVienActionPerformed(evt);
            }
        });

        btnDsKhachHang.setBackground(new java.awt.Color(51, 51, 255));
        btnDsKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/khachhang.png"))); // NOI18N
        btnDsKhachHang.setText("Danh sách khách hàng");
        btnDsKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsKhachHangActionPerformed(evt);
            }
        });

        btnDanSachNhaCungCap.setBackground(new java.awt.Color(51, 102, 255));
        btnDanSachNhaCungCap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/supplier.png"))); // NOI18N
        btnDanSachNhaCungCap.setText("Danh sách nhà cung cấp");
        btnDanSachNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDanSachNhaCungCapActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 51, 51));
        btnExit.setForeground(new java.awt.Color(51, 0, 51));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exit.png"))); // NOI18N
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnDsHoaDon.setBackground(new java.awt.Color(51, 51, 255));
        btnDsHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/bill.png"))); // NOI18N
        btnDsHoaDon.setText("Danh sách hóa đơn");

        btnDsTraSua.setBackground(new java.awt.Color(51, 51, 255));
        btnDsTraSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/product.png"))); // NOI18N
        btnDsTraSua.setText("Danh sách trà sữa");
        btnDsTraSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsTraSuaActionPerformed(evt);
            }
        });

        btnNhapSanPham.setBackground(new java.awt.Color(51, 51, 255));
        btnNhapSanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nhom11_qltrasua/product.png"))); // NOI18N
        btnNhapSanPham.setText("Nhập sản phẩm");
        btnNhapSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapSanPhamActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trà sữa 11 Central");

        lblLogo.setText("Logo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnDsNhanVien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDsKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDanSachNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDsHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDsTraSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNhapSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(36, 36, 36)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDsNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDanSachNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDsKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnExit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnDsHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnDsTraSua, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(btnNhapSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65))))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDsNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsNhanVienActionPerformed
frmNhanVien nhanVien = new frmNhanVien();
nhanVien.setVisible(true);
this.dispose();
       
    }//GEN-LAST:event_btnDsNhanVienActionPerformed

  
       
   public void showLogoStore()
   {
        ImageIcon imageIcon = new ImageIcon("src\\Img\\Logo.png");
              Image image = imageIcon.getImage().getScaledInstance(235,230, Image.SCALE_SMOOTH);
              lblLogo.setIcon(new ImageIcon(image));
              return;

   }
    
    private void btnDsTraSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsTraSuaActionPerformed
        try {
            // TODO add your handling code here:
            frmDanhSachTraSua danhSachTraSua = new frmDanhSachTraSua();
            danhSachTraSua.setVisible(true);
            this.setVisible(false);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnDsTraSuaActionPerformed

    private void btnDsKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsKhachHangActionPerformed
        // TODO add your handling code here:
        frmKhachHang khachHang = new frmKhachHang();
        khachHang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDsKhachHangActionPerformed

    private void btnNhapSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapSanPhamActionPerformed
        // TODO add your handling code here:
        NhapTraSua nhapTraSua = new  NhapTraSua();
        nhapTraSua.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnNhapSanPhamActionPerformed

    private void btnDanSachNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDanSachNhaCungCapActionPerformed
        // TODO add your handling code here:
       
       
            NhanVien nhanVien = new NhanVien();
//            Connection connection = KetNoi.connectToDatabase();
//              String sql = "select MAQUYEN  from QUYEN where TAIKHOAN  = '" +lblTaiKhoan.getText().toString()+ "'";
//              Statement st = connection.createStatement();
//              ResultSet rs = st.executeQuery(sql); 
//                if (rs.next()) 
//                { // Kiểm tra nếu ResultSet có dữ liệu
//        String  = rs.getString("MAQUYEN").substring(0, 2);
//        JOptionPane.showMessageDialog(this,"Quyền của bạn là" + ma);
//                }
//              String ma = nhanVien.taiKhoan.substring(0,5);
//           if(ma.equals("admin"))
//           {
                frmNhaCungCap formNhaCungCap = new frmNhaCungCap();
                 formNhaCungCap.setVisible(true);
                  this.setVisible(false);
//           }
//           else 
//               JOptionPane.showMessageDialog(null, "Bạn không có quyên truy cập vào chức năng này");
      
        
    }//GEN-LAST:event_btnDanSachNhaCungCapActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        frmDangNhap Login = new frmDangNhap();
        PhanQuyen.xoaPhanQuyen();
        Login.setVisible(true);
        this.setVisible(false);
       
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        frmDatTraSua datTraSua = new frmDatTraSua();
        datTraSua.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new frmMain().setVisible(true);
//                NhanVien nhanVien = new NhanVien();
//                if (nhanVien.taiKhoan.substring(0, 5).equals("admin"))
//                {
//                    btnDanSachNhaCungCap.setEnabled(false);
//                }
            }
        });
    }

//     private void hienThiTenNhanVien()
//    {
//        PhanQuyen phanQuyen = new PhanQuyen();
//        if(phanQuyen.getTaiKhoanCu().equals("admin"))
//        lblAdmin.setText("welcome: " + phanQuyen.getTaiKhoanCu().toString());
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDanSachNhaCungCap;
    private javax.swing.JButton btnDsHoaDon;
    private javax.swing.JButton btnDsKhachHang;
    private javax.swing.JButton btnDsNhanVien;
    private javax.swing.JButton btnDsTraSua;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNhapSanPham;
    private javax.swing.JButton btnOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
