/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nhom11_qltrasua;

import Model.NhanVien;
import Model.KetNoi;
import Model.PhanQuyen;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.ButtonType;
import javax.net.ssl.SSLEngineResult;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.parser.DTDConstants;

/**
 *
 * @author Nguyen Cat Tuong
 */
public class frmNhaCungCap extends javax.swing.JFrame {

    /**
     * Creates new form frmNhaCungCap
     */
    public frmNhaCungCap() {
        initComponents();
        makeNhaCungCapId();
        loadNhaCungCap();
        
    }
    
    private void displayNhaCungCap()
    {
        int selectedRow = tblDsNhaCungCap.getSelectedRow();
        
        if (selectedRow != -1)
        {
            txtMaNhaCungCap.setText(String.valueOf(tblDsNhaCungCap.getValueAt(selectedRow, 0)));
            txtTenNhaCungCap.setText(String.valueOf(tblDsNhaCungCap.getValueAt(selectedRow, 1)));
            txtSoDienThoai.setText(String.valueOf(tblDsNhaCungCap.getValueAt(selectedRow, 2)));

        }
    }
    
    private void loadNhaCungCap()
    {
         try 
        {
        
            Connection con = KetNoi.connectToDatabase();
         
            String sql= "select MaNCC as N'Mã Nhà Cung Cấp', TenNCC as N'Tên Nhà Cung Cấp', SDT as N'Số Điện Thoại' from NhaCungCap where TrangThai = 1";
            Statement st = (Statement) con.createStatement();
//            if(con != null)
//                JOptionPane.showMessageDialog(null, "kết nối thành công");
              DefaultTableModel defaultTableModel = (DefaultTableModel) tblDsNhaCungCap.getModel();
            ResultSet rs = st.executeQuery(sql);
            defaultTableModel.setRowCount(0);
                while (rs.next())
                {
                     Object object[] = {rs.getString("Mã Nhà Cung Cấp"),rs.getString("Tên Nhà Cung Cấp"),rs.getString("Số Điện Thoại")};
                     defaultTableModel.addRow(object);
                }
           
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(frmDanhSachTraSua.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDsNhaCungCap = new javax.swing.JTable();
        txtMaNhaCungCap = new javax.swing.JTextField();
        txtTenNhaCungCap = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tbnThemMoi = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nhà cung cấp");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhà cung cấp");

        jLabel2.setText("Mã nhà cung cấp");

        jLabel3.setText("Tên nhà cung cấp");

        jLabel4.setText("Số điện thoại ");

        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblDsNhaCungCap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Số Điện Thoại"
            }
        ));
        tblDsNhaCungCap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDsNhaCungCapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblDsNhaCungCapMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tblDsNhaCungCap);

        txtMaNhaCungCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhaCungCapActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Danh sách nhà cung cấp");

        tbnThemMoi.setText("Thêm mới");
        tbnThemMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnThemMoiActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel6.setText("Tìm kiếm nhà cung cấp:");

        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNhaCungCap)
                            .addComponent(txtSoDienThoai)
                            .addComponent(txtMaNhaCungCap)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTimKiem)
                                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tbnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnThemMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
            try 
        {
       Connection con = KetNoi.connectToDatabase();
           String sql = "update NhaCungCap set TrangThai = ? where MaNCC = ?";
           PreparedStatement st = con.prepareStatement(sql);
           st.setInt(1, 0);
           st.setString(2,txtMaNhaCungCap.getText());
           int check = st.executeUpdate();
           if(check  > 0 )
               JOptionPane.showMessageDialog(null, "Xóa thành công");
            con.close();
            clearText();
            loadNhaCungCap();
        } catch (SQLException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       
              try 
        {
            for(char c : txtSoDienThoai.getText().toCharArray())
            {
               
             if(!Character.isDigit(c))
             { JOptionPane.showMessageDialog(null, "Số điện thoại phải là số");
                             txtSoDienThoai.requestFocus();
             return;
             }
            }
            
            if(!(txtSoDienThoai.getText().length() == 10))
            {
                JOptionPane.showMessageDialog(null, "Số điện thoại phải 10 số");
                txtSoDienThoai.requestFocus();
                return;
            }
             String soDau = txtSoDienThoai.getText().substring(0, 1);
             if (Integer.parseInt(soDau) != 0)
             {
                 JOptionPane.showMessageDialog(null, "Đầu số điện thoại phải là 0");
                 txtSoDienThoai.requestFocus();
                return;
             }
            
            
           Connection con = KetNoi.connectToDatabase();
            String sql= "insert into NhaCungCap values (?,?,?,?)";
            PreparedStatement st =  con.prepareStatement(sql);
             
//            if(con != null)
//                JOptionPane.showMessageDialog(null, "kết nối thành công");
            
            st.setString(1,txtMaNhaCungCap.getText());
            st.setString(2,txtTenNhaCungCap.getText());
            st.setString(3,txtSoDienThoai.getText());
            st.setInt(4, 1);
            st.executeUpdate();
            st.close();
//            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Thêm thành công.");
            con.close();
            clearText();
           
        } catch (SQLException ex) {
            Logger.getLogger(frmDanhSachTraSua.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        tblDsNhaCungCap.clearSelection();
        loadNhaCungCap();
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblDsNhaCungCapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsNhaCungCapMouseClicked
        // TODO add your handling code here:
        displayNhaCungCap();
    }//GEN-LAST:event_tblDsNhaCungCapMouseClicked
    
    private void makeNhaCungCapId() 
    {
        try
        {
            String user="sa";
            String pass="123";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://DESKTOP-KSEC4J7\\SQLEXPRESS:1433;databaseName=QL_QUAN_TRA_SUA";
            Connection con;
            con = DriverManager.getConnection(url, user,pass);
            
            String sql= "select count(*) from NhaCungCap";
            
            Statement st = (Statement) con.createStatement();
            ResultSet result = st.executeQuery(sql);
            
            int number = 0;
            while (result.next())
            {
                 number  = result.getInt(1);
               
            }

            if (number >= 0 && number < 10)
                txtMaNhaCungCap.setText("S000" + String.valueOf(number + 1));
            else if (number >= 10 && number < 100) 
                txtMaNhaCungCap.setText("S00" + String.valueOf(number +1));
            else if (number >= 100 && number < 1000)
                txtMaNhaCungCap.setText("S0" + String.valueOf(number + 1));
            else if (number >= 1000 && number < 10000)
                txtMaNhaCungCap.setText("S" + String.valueOf(number +1));
            else
                JOptionPane.showMessageDialog(null, "Hóa đơn trong cơ sở dữ liệu đã đầy. Vui lòng liên hệ nhà phát triển để tăng ô chứa dữ liệu!");
        } catch (SQLException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }
    
    private void clearText()
    {
        txtMaNhaCungCap.setText("");
        txtTenNhaCungCap.setText("");
        txtSoDienThoai.setText("");

    }
    
    
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
       if(txtMaNhaCungCap.getText().isEmpty())
           JOptionPane.showMessageDialog(null, "Hãy điền mã nhà cung cấp");
//       
       try 
       {
            String user="sa";
            String pass="123";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String url="jdbc:sqlserver://DESKTOP-KSEC4J7\\SQLEXPRESS:1433;databaseName=QL_QUAN_TRA_SUA";
            Connection con;
                con = DriverManager.getConnection(url, user,pass);
            
           
           String sql = "update NhaCungCap set TenNCC = ?, SDT = ? where MaNCC = ?";
           PreparedStatement st = con.prepareStatement(sql);
           st.setString(1,txtTenNhaCungCap.getText());
           st.setString(2,txtSoDienThoai.getText());
           st.setString(3,txtMaNhaCungCap.getText());
           
           int check = st.executeUpdate();
           if(check  > 0 )
               JOptionPane.showMessageDialog(null, "Cập nhật thành công");
            con.close();
            clearText();
            loadNhaCungCap();
       } catch (ClassNotFoundException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbnThemMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnThemMoiActionPerformed
        // TODO add your handling code here:
        clearText();
        makeNhaCungCapId();
    }//GEN-LAST:event_tbnThemMoiActionPerformed

    private void txtMaNhaCungCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhaCungCapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhaCungCapActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
      PhanQuyen  phanQuyen = new PhanQuyen();
if(phanQuyen.getTaiKhoanCu().equals("admin"))
{
       frmMain m = new frmMain();
        m.setVisible(true);
        this.dispose();
}
else 
{
    frmMainNhanVien nhanVien = new frmMainNhanVien();
    nhanVien.setVisible(true);
    this.dispose();;
}
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void timKiemNhaCungCap()
    {
        try
        {
         ArrayList<String> strings = new  ArrayList<>  ();
//         tblDsNhaCungCap.clearSelection();
        Connection connection = KetNoi.connectToDatabase();
        Statement st = connection.createStatement();
        String sql = "select * from NhaCungCap where TenNCC like N'%" +txtTimKiem.getText().toString()+"%'";
        ResultSet rs = st.executeQuery(sql);
        DefaultTableModel defaultTableModel = (DefaultTableModel) tblDsNhaCungCap.getModel();
        defaultTableModel.setRowCount(0);
       while (rs.next())
       {
           Object o[] = {rs.getString("MaNCC"),rs.getString("TenNCC"),rs.getString("SDT")};
           defaultTableModel.addRow(o);
       }
        } catch (SQLException ex) {
            Logger.getLogger(frmNhaCungCap.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
                timKiemNhaCungCap();

        
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblDsNhaCungCapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDsNhaCungCapMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblDsNhaCungCapMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tblDsNhaCungCap;
    private javax.swing.JButton tbnThemMoi;
    private javax.swing.JTextField txtMaNhaCungCap;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhaCungCap;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
