/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom11_qltrasua;

import java.awt.Color;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import Model.KetNoi;

/**Đ
 *
 * @author nguye
 */
public class NhapHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form HoaDon
     */
    
    public NhapHoaDon() {
        initComponents();
        
        layIDHoaDon();
        layTenNV();
        layMaKH();
        laySdtKH();
        laytongTien();
        layMaNV();
        laySdtNV();
        layTenKH();
                ShowDuLieu();

    }
    private void ShowDuLieu() {
        try {
            tbchitiethd.removeAll();
            String[] arr = {"Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Giá bán", "Thành tiền"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            Connection connection = KetNoi.connectToDatabase();
            String query = "select TRASUA.MATRASUA, TRASUA.TENTRASUA, TRASUA.GiaBan, ChiTietHoaDon.SoLuong, ChiTietHoaDon.ThanhTien from TRASUA JOIN ChiTietHoaDon on  ChiTietHoaDon.MATRASUA = TRASUA.MATRASUA and ChiTietHoaDon.MaHDB = '" +lblMaHDB.getText()+"'";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                Vector vector = new Vector();
                vector.add(rs.getString("MATRASUA"));
                vector.add(rs.getString("TENTRASUA"));
                vector.add(rs.getString("GiaBan"));
                vector.add(rs.getString("SoLuong"));
                vector.add(rs.getString("ThanhTien"));
                model.addRow(vector);
            }
            tbchitiethd.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbtennv = new javax.swing.JLabel();
        lblMaHDB = new javax.swing.JLabel();
        lbsdtkh = new javax.swing.JLabel();
        lbmakh = new javax.swing.JLabel();
        lbsdtnv = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lbmanv = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txttienkhachdua = new javax.swing.JTextField();
        lbtongtien = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        btnthem1 = new javax.swing.JButton();
        lbtientrakhach = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbchitiethd = new javax.swing.JTable();
        btnXacNhan = new javax.swing.JButton();
        btnthem2 = new javax.swing.JButton();

        jLabel12.setText("jLabel12");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("HÓA ĐƠN");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thanh Toán"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Số điện thoại KH:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tên nhân viên:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Mã hóa đơn:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Ten KH:");

        lbtennv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbtennv.setText("jLabel13");

        lblMaHDB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMaHDB.setText("jLabel15");

        lbsdtkh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsdtkh.setText("jLabel16");

        lbmakh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmakh.setText("jLabel18");

        lbsdtnv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbsdtnv.setText("jLabel13");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Số điện thoại NV:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mã nhân viên:");

        lbmanv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbmanv.setText("jLabel13");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbmakh)
                    .addComponent(lbsdtkh)
                    .addComponent(lblMaHDB))
                .addGap(221, 221, 221)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(lbsdtnv))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbmanv)
                            .addComponent(lbtennv))))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(lbmanv))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(lblMaHDB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lbtennv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lbsdtnv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(lbmakh))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbsdtkh)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sự kiện hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tổng tiền:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Tiền khách đưa:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Tiền trả khách:");

        txttienkhachdua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txttienkhachduaFocusLost(evt);
            }
        });

        lbtongtien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnreset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnreset.setText("Hủy");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btnthem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthem1.setText("Thanh toán");
        btnthem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem1ActionPerformed(evt);
            }
        });

        lbtientrakhach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnreset)
                .addGap(18, 18, 18)
                .addComponent(btnthem1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbtientrakhach))
                        .addContainerGap(110, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lbtongtien)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbtongtien))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttienkhachdua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtientrakhach))
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem1)
                    .addComponent(btnreset))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi Tiết Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        tbchitiethd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbchitiethd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbchitiethdMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbchitiethd);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(317, 317, 317))
        );

        btnXacNhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXacNhan.setText("Xác nhận đã thanh toán chuyển khoản");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnthem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthem2.setText("Thanh toán chuyển khoản");
        btnthem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXacNhan)
                            .addComponent(btnthem2, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnthem2)
                        .addGap(28, 28, 28)
                        .addComponent(btnXacNhan)
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbchitiethdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbchitiethdMouseClicked
        // TODO add your handling code here:
        int x = tbchitiethd.getSelectedRow();
        if (x >= 0){
//            txthd.setText(tbchitiethd.getValueAt(x, 0) + "");
//            txttrasua.setText(tbchitiethd.getValueAt(x, 1) + "");
//            txtsoluong.setText(tbchitiethd.getValueAt(x, 2) + "");
//            txtgiamgia.setText(tbchitiethd.getValueAt(x, 3) + "");
//            txtthanhtien.setText(tbchitiethd.getValueAt(x, 4) + "");
            
        }
        
    }//GEN-LAST:event_tbchitiethdMouseClicked

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
       frmDatTraSua datTraSua = new frmDatTraSua();
       datTraSua.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btnthem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem1ActionPerformed
JOptionPane.showMessageDialog(null, "Thanh toán thành công");
lbtientrakhach.setText("");
txttienkhachdua.setText("");
lbtongtien.setText("0");
    }//GEN-LAST:event_btnthem1ActionPerformed

    private void btnthem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem2ActionPerformed
        // TODO add your handling code here:
        ThanhToanTrucTuyen thanhToanTrucTuyen = new ThanhToanTrucTuyen();
        thanhToanTrucTuyen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnthem2ActionPerformed

    private void txttienkhachduaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txttienkhachduaFocusLost
        // TODO add your handling code here:
        if(txttienkhachdua.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Bạn chưa nhập tiền khách đưa");
            txttienkhachdua.requestFocus();
            return;
        }
        tienTraKhach();
    }//GEN-LAST:event_txttienkhachduaFocusLost

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        lbtientrakhach.setText("");
txttienkhachdua.setText("");
lbtongtien.setText("0");
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void layIDHoaDon()
    {
        try
        {
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TOP 1 MAHDB FROM HoaDonBan ORDER BY MaHDB DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lblMaHDB.setText(rs.getString("MaHDB"));
                lblMaHDB.setForeground(Color.blue);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }
    
    private String layMaNhanVienCuoiCung()
    {
        String maNV = null;
           try {
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TOP 1 MANV FROM HoaDonBan ORDER BY MaHDB DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                maNV = rs.getString("MANV");
        }catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
           return maNV;
    }
    
    private void layTenNV() {
        try {
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TENNV  FROM NHANVIEN where MANV = '"+layMaNhanVienCuoiCung()+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lbtennv.setText(rs.getString("TENNV"));
                lbtennv.setForeground(Color.blue);
        }catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
     private void layTenKH() {
        try {
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TENKH  FROM KHACHHANG where MAKH = '"+layMaKH()+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lbmakh.setText(rs.getString("TENKH"));
                lbmakh.setForeground(Color.blue);
        }catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    private String layMaKH() {
         String maKH = null;
        try
        {
           
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TOP 1 MAKH FROM KHACHHANG ORDER BY MAKH DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
            {
//                lbmakh.setText(rs.getString("MaKH"));
//                lbmakh.setForeground(Color.blue);
              maKH =   rs.getString("MaKH");
            }
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
                        return maKH;

    }
    
    private void laySdtKH() {
        try
        {
            Connection conn = KetNoi.connectToDatabase();
           String sql = "SELECT SDT  FROM KHACHHANG where MAKH = '"+layMaKH()+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lbsdtkh.setText(rs.getString("SDT"));
                lbsdtkh.setForeground(Color.blue);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    private void layMaNV() {
        lbmanv.setText(layMaNhanVienCuoiCung());
           lbmanv.setForeground(Color.blue);
    }
    
    private void laySdtNV() {
          try
        {
            Connection conn = KetNoi.connectToDatabase();
           String sql = "SELECT SDT  FROM NHANVIEN where MANV = '"+layMaNhanVienCuoiCung()+"'";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lbsdtnv.setText(rs.getString("SDT"));
                lbsdtnv.setForeground(Color.blue);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    private void laytongTien() {
        try
        {
            Connection conn = KetNoi.connectToDatabase();
            String sql = "SELECT TOP 1 TongTienBan FROM HoaDonBan ORDER BY MaHDB DESC";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            if(rs.next())
                lbtongtien.setText(rs.getString("TongTienBan"));
                lbtongtien.setForeground(Color.blue);
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
    
    private void tienTraKhach() {
        float tienKhachDua = Float.parseFloat(txttienkhachdua.getText());
        
        lbtientrakhach.setText(String.valueOf(tinhTongTien(tienKhachDua)));
        
    }
    private float layTongTien(String maHoaDonBan)
    {
        float tongTien = 0;
      
        try
        {
              Connection connection = KetNoi.connectToDatabase();
            String sql = "select TongTienBan from HoaDonBan where MaHDB = '"
+maHoaDonBan+"'";  
        Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
        if(rs.next())
        {
            tongTien = rs.getFloat("TongTienBan");
        }
        } catch (SQLException ex) {
            Logger.getLogger(NhapHoaDon.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        return tongTien;
    }
    
    public  double tinhTongTien(float tienKhachDua) {
        float tienTra = 0;
    
       float tongTien = layTongTien(lblMaHDB.getText());
       tienTra = tienKhachDua - tongTien;
       return tienTra;
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NhapHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnthem1;
    private javax.swing.JButton btnthem2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMaHDB;
    private javax.swing.JLabel lbmakh;
    private javax.swing.JLabel lbmanv;
    private javax.swing.JLabel lbsdtkh;
    private javax.swing.JLabel lbsdtnv;
    private javax.swing.JLabel lbtennv;
    private javax.swing.JLabel lbtientrakhach;
    private javax.swing.JLabel lbtongtien;
    private javax.swing.JTable tbchitiethd;
    private javax.swing.JTextField txttienkhachdua;
    // End of variables declaration//GEN-END:variables
}
