/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nhom11_qltrasua;

import Controller.DatTraSuaController;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import Model.KetNoi;
import Model.PhanQuyen;
import Model.TraSua;
/**
 *
 * @author nguye
 */
public class NhapTraSua extends javax.swing.JFrame {


    /**
     * Creates new form NhapTraSua
     */
    ArrayList<TraSua> lsTS = new ArrayList<>();
    String filename = null;
    byte[] trasua_image = null;
    public NhapTraSua() {
        initComponents();
        ShowDuLieu();
        tuSinhMa();
       
        
    }
   
//    public void LoadDataArrayToTable(){
//        DefaultTableModel model = (DefaultTableModel) tbdanhsachsp.getModel();
//        model.setRowCount(0);
//        for(TraSua ts: arr)
//        {
//            model.addRow(new Object[]{ts.getMaTS(), ts.getTenTS(), ts.getGiaSP()});
//        }
//    }

    private void ShowDuLieu() {
        try {
            tbdanhsachsp.removeAll();
            String[] arr = {"Mã Trà Sữa", "Tên Trà Sữa", "Giá Bán", "Nhà Cung Cấp", "Giá Nhập"};
            DefaultTableModel model = new DefaultTableModel(arr, 0);

            Connection connection = KetNoi.connectToDatabase();
            String query = "select TRASUA.MATRASUA, TRASUA.TENTRASUA, TRASUA.GiaBan, TRASUA.GiaNhap, NhaCungCap.TenNCC,TRASUA.IdHinh from TRASUA JOIN NhaCungCap on TRASUA.MaNCC = NhaCungCap.MaNCC";
            PreparedStatement ps = connection.prepareStatement(query);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                Vector vector = new Vector(); 
                vector.add(rs.getString("MATRASUA"));
                vector.add(rs.getString("TENTRASUA"));
                vector.add(rs.getString("GiaBan"));  
                vector.add(rs.getString("TenNCC"));
                vector.add(rs.getString("GiaNhap"));
                vector.add(rs.getBytes("IdHinh"));
                lsTS.add(new TraSua(rs.getString("MATRASUA"), rs.getString("TENTRASUA"),rs.getFloat("GiaBan"),rs.getFloat("GiaNhap"),rs.getString("TenNCC") , rs.getString("IdHinh")));
                model.addRow(vector);
            }
            tbdanhsachsp.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(NhapTraSua.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tuSinhMa()
    {
        txtmats.setText(taoMaTraSua());
    }
   
     public String taoMaTraSua()
     {
         String idTraSua = "";
        try
        {
             Connection con;
            con = KetNoi.connectToDatabase();
            String sql= "select count(*) from TRASUA";
            
            Statement st = (Statement) con.createStatement();
            ResultSet result = st.executeQuery(sql);
            
            int number = 0;
            while (result.next())
            {
                 number  = result.getInt(1);
               
            }
             if (number >= 0 && number < 10)
                idTraSua = "TS00" + String.valueOf(number + 1);
            else if (number >= 10 && number < 100) 
                idTraSua ="TS0" + String.valueOf(number +1);
            else if (number >= 100 && number < 1000)
                idTraSua = "TS" + String.valueOf(number + 1);
            else
                JOptionPane.showMessageDialog(null, "Dữ liệu đã đầy. Vui lòng liên hệ nhà phát triển để tăng ô chứa dữ liệu!");
        } catch (SQLException ex) {
             Logger.getLogger(DatTraSuaController.class.getName()).log(Level.SEVERE, null, ex);
         }
        return idTraSua;
     }
    
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txttensp = new javax.swing.JTextField();
        txtmats = new javax.swing.JTextField();
        txtncc = new javax.swing.JTextField();
        txtgiasp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdanhsachsp = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btncapnhat = new javax.swing.JButton();
        btnthoat = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        lb_photo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtgianhap = new javax.swing.JTextField();
        btnimage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("NHẬP TRÀ SỮA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã trà sữa:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Tên trà sữa:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhà cung cấp:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giá sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tìm kiếm sản phẩm theo danh sách:");

        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });
        txttimkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimkiemKeyReleased(evt);
            }
        });

        tbdanhsachsp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbdanhsachsp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdanhsachspMouseClicked(evt);
            }
        });
        tbdanhsachsp.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tbdanhsachspComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tbdanhsachsp);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnthem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/add.png"))); // NOI18N
        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btncapnhat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btncapnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fix.png"))); // NOI18N
        btncapnhat.setText("Sửa");
        btncapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatActionPerformed(evt);
            }
        });

        btnthoat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnthoat.setText("Thoát");
        btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/reset.png"))); // NOI18N
        btnreset.setText("Làm mới");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnthem)
                .addGap(48, 48, 48)
                .addComponent(btnxoa)
                .addGap(45, 45, 45)
                .addComponent(btncapnhat)
                .addGap(40, 40, 40)
                .addComponent(btnreset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnthoat)
                .addGap(52, 52, 52))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthem)
                        .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btncapnhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnthoat)
                        .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        lb_photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        lb_photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_photoMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Giá nhập:");

        txtgianhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgianhapActionPerformed(evt);
            }
        });

        btnimage.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnimage.setText("Chọn ảnh");
        btnimage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnimageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtmats, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)))
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtgiasp)
                                    .addComponent(txtncc, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(79, 79, 79)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_photo, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btnimage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(lb_photo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtmats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtgiasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtgianhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnimage))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void resetForm() {
        txtmats.setText("");
        txttensp.setText("");  
        txtgiasp.setText("");
        txtgianhap.setText("");
        txtmats.requestFocus();
        txtncc.setText("");
    }
    private void btnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatActionPerformed
        // TODO add your handling code here:
         PhanQuyen  phanQuyen = new PhanQuyen();
if(phanQuyen.getTaiKhoanCu().equals("admin"))
{
       frmMain m = new frmMain();
        m.setVisible(true);
        this.dispose();
}
else 
{
    frmMainNhanVien nhanVien = new frmMainNhanVien();
    nhanVien.setVisible(true);
    this.dispose();;
}
    }//GEN-LAST:event_btnthoatActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xóa ?" );
        if (result == 0) {
            int position = tbdanhsachsp.getSelectedRow();
            String data = tbdanhsachsp.getModel().getValueAt(position, 0).toString();
            try {
                Connection connection = KetNoi.connectToDatabase();
                String query = "DELETE FROM TRASUA WHERE MaTS = ?";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, data);
                ps.executeUpdate();
                ShowDuLieu();
                connection.close();
                JOptionPane.showMessageDialog(null, "Xóa thành công !");
            }catch (SQLException ex){
                ex.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnxoaActionPerformed

    private void tbdanhsachspMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdanhsachspMouseClicked
        // TODO add your handling code here:
        int x = tbdanhsachsp.getSelectedRow();
        if (x >= 0){
            txtmats.setText(tbdanhsachsp.getValueAt(x, 0) + "");
            txttensp.setText(tbdanhsachsp.getValueAt(x, 1) + "");
            txtgiasp.setText(tbdanhsachsp.getValueAt(x, 2) + ""); 
            txtncc.setText(tbdanhsachsp.getValueAt(x, 3) + "");
            txtgianhap.setText(tbdanhsachsp.getValueAt(x, 4) + "");
     
        }
        
           
       String hinhanh = (lsTS.get(x).getIdHinh());
         ImageIcon imageIcon = new ImageIcon("src\\Img\\" + hinhanh);
              Image image = imageIcon.getImage().getScaledInstance(160,200, Image.SCALE_SMOOTH);
            lb_photo.setIcon(new ImageIcon(image));  
    }//GEN-LAST:event_tbdanhsachspMouseClicked

    public boolean checkTrungMATS() {
        try {
            Connection connection = KetNoi.connectToDatabase();
            String query = "SELECT *FROM TRASUA WHERE MaTS = ? ";
            PreparedStatement ps = connection.prepareStatement(query);
            ps.setString(1, txtmats.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                return true;
            }
            connection.close();
        }catch (SQLException ex){
            Logger.getLogger(NhapTraSua.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = KetNoi.connectToDatabase();
        } catch (SQLException ex) {
            Logger.getLogger(NhapTraSua.class.getName()).log(Level.SEVERE, null, ex);
        }

            if (txtmats.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Mã Trà Sữa không được bỏ trống");
            txtmats.requestFocus();
            return;
        }else if (txttensp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Tên Trà Sữa không được bỏ trống");
            txttensp.requestFocus();
            return;
        }else if (txtgiasp.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Giá sản phẩm không được bỏ trống");
            txtgiasp.requestFocus();
            return;
        }else if (txtgianhap.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Giá nhập không được bỏ trống");
            txtgianhap.requestFocus();
            return;
        }else if (txtncc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Nhà cung cấp không được bỏ trống");
            txtncc.requestFocus();
            return;
        }else {
            String mats = txtmats.getText();
            if(mats.length() > 6){
                JOptionPane.showMessageDialog(null, "Mã trà sữa không đúng định dạng. Hãy nhập lại !");
                txtmats.requestFocus();
                return;
            }
        }
        if(checkTrungMATS() == true )
        {
            JOptionPane.showMessageDialog(null,"Mã trà sữa đã tồn tại !!");
            txtmats.requestFocus();
            return;
        }else {
            try {
                Connection connection = KetNoi.connectToDatabase();
                String query = "INSERT INTO TRASUA(MaTS, TenTS, GiaBan, GiaNhap, MaNCC, IdHinh)"
                        + "VALUES (?,?,?,?,?,?)";
                PreparedStatement ps = connection.prepareStatement(query);
                ps.setString(1, txtmats.getText());
                ps.setString(2, txttensp.getText());
                ps.setString(3, txtgiasp.getText());
                ps.setString(4, txtgianhap.getText());
                ps.setString(5, txtncc.getText());
                ps.setBytes(6, trasua_image);
                ps.executeUpdate();
                ShowDuLieu();
                connection.close();
                JOptionPane.showMessageDialog(null, "Thêm thành công !");
            }catch (SQLException ex) {
                ex.printStackTrace();
        }         
        resetForm();  
        } 
    }//GEN-LAST:event_btnthemActionPerformed

    private void btncapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatActionPerformed
        // TODO add your handling code here:
        try {
            if (txtmats.getText().equals("") || txttensp.getText().equals("") || txtgiasp.getText().equals("")|| txtgianhap.getText().equals("") || txtncc.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Cần phải nhập dữ liệu !");
            } else {
//                Connection connection = DBConnection.getConnection();
//                int row = tbdanhsachsp.getSelectedRow();
//                String value = (tbdanhsachsp.getModel().getValueAt(row, 0).toString());
//                String query = "UPDATE TRASUA SET TenTS = ?,GiaBan = ?,GiaNhap = ?, MaNCC = ?, IdHinh = ? WHERE MaTS = ? "+ value ;
//            PreparedStatement ps = connection.prepareStatement(query);
//            ps.setString(1,txtmats.getText());  
//            ps.setString(2,txttensp.getText()); 
//            ps.setString(3,txtgiasp.getText());
//            ps.setString(4,txtgianhap.getText());
//            ps.setString(5, txtncc.getText());
//            ps.executeUpdate();
//            DefaultTableModel model = (DefaultTableModel) tbdanhsachsp.getModel();
//            model.setRowCount(0);
//            ShowDuLieu();
//          
//            JOptionPane.showMessageDialog(null, "Cập nhật thành công!!!"); 
//            }  
//            }catch (SQLException ex){
//                ex.printStackTrace();

            DefaultTableModel model = (DefaultTableModel) tbdanhsachsp.getModel();
            if(tbdanhsachsp.getSelectedRowCount()==1) {
                String ma = txtmats.getText();
                String ten = txttensp.getText();
                String gia= txtgiasp.getText();
                String gianh = txtgianhap.getText();
                String ncc = txtncc.getText();
                
                model.setValueAt(ma, tbdanhsachsp.getSelectedRow(), 0);
                model.setValueAt(ten, tbdanhsachsp.getSelectedRow(), 1);
                model.setValueAt(gia, tbdanhsachsp.getSelectedRow(), 2);
                model.setValueAt(gianh, tbdanhsachsp.getSelectedRow(), 4);
                model.setValueAt(ncc, tbdanhsachsp.getSelectedRow(), 3);
                JOptionPane.showMessageDialog(null, "Cập nhật thành công!!!");
            }else {
                if(tbdanhsachsp.getRowCount()==0) {
                    JOptionPane.showMessageDialog(this, "empty");
                }else {
                    JOptionPane.showMessageDialog(this, "plese");
                }
            }
            }
        }catch (Exception ex){
                ex.printStackTrace();
        }
                resetForm();
    }//GEN-LAST:event_btncapnhatActionPerformed

    
    private void tbdanhsachspComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tbdanhsachspComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbdanhsachspComponentShown

    private void txttimkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimkiemKeyReleased
        // TODO add your handling code here:
        DefaultTableModel ojb = (DefaultTableModel) tbdanhsachsp.getModel();
        TableRowSorter<DefaultTableModel> ojbl = new TableRowSorter<>(ojb);
        tbdanhsachsp.setRowSorter(ojbl);
        ojbl.setRowFilter(RowFilter.regexFilter(txttimkiem.getText()));
    }//GEN-LAST:event_txttimkiemKeyReleased

    private void lb_photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_photoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lb_photoMouseClicked

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_btnresetActionPerformed

    private void txtgianhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgianhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgianhapActionPerformed
    private void loadImage() throws  IOException  {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        lb_photo.setIcon(new ImageIcon(file.toString()));
        filename = file.getAbsolutePath();
        lb_photo.setText(filename);
        FileInputStream fis = new FileInputStream(file);
        
        
    }
    
    private void btnimageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnimageActionPerformed
//         TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lb_photo.getWidth(), lb_photo.getHeight(), Image.SCALE_SMOOTH));
        lb_photo.setIcon(imageIcon);
        try{
            File image = new File(filename);
            FileInputStream fis = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte [] buf = new byte[1024];
            for (int readNum; (readNum = fis.read(buf)) != -1;){
                bos.write(buf, 0, readNum);
            }
            trasua_image = bos.toByteArray();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnimageActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NhapTraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NhapTraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NhapTraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NhapTraSua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new NhapTraSua().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhat;
    private javax.swing.JButton btnimage;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthoat;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_photo;
    private javax.swing.JTable tbdanhsachsp;
    private javax.swing.JTextField txtgianhap;
    private javax.swing.JTextField txtgiasp;
    private javax.swing.JTextField txtmats;
    private javax.swing.JTextField txtncc;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables

}
